#!/usr/bin/env bash
# Rebuild the vendored Supabase client.
#
# The panel used to `import { createClient } from "https://esm.sh/..."` at
# runtime, and the Tauri CSP was widened to permit it. That put a third-party CDN
# inside the trust boundary of a desktop app: a compromise or hijack of that host
# would execute arbitrary JavaScript in a webview holding the user's auth session,
# with reach into the local control API. For a product whose entire pitch is that
# nothing leaves your machine, fetching executable code from someone else's server
# on every launch is the wrong default.
#
# So the SDK is bundled once, committed, and loaded from disk. Re-run this to
# change versions; the pinned version below is the single source of truth.
#
#   apps/desktop/ui/scripts/vendor-supabase.sh
set -euo pipefail

VERSION="2.47.10"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
UI="$(cd "$HERE/.." && pwd)"
LANDING="$(cd "$UI/../../landing" && pwd)"

cd "$UI"
npm install --no-save --silent "@supabase/supabase-js@${VERSION}" esbuild

for out in "$UI/vendor/supabase.js" "$LANDING/vendor/supabase.js"; do
  mkdir -p "$(dirname "$out")"
  # `--legal-comments=eof` keeps the licence text the bundled packages carry.
  # They are MIT, which requires the copyright and permission notice to travel
  # with any redistributed copy — and a vendored bundle shipped inside every
  # installer is exactly a redistributed copy. Stripping them (the default when
  # minifying) would have made every release non-compliant, quietly.
  ./node_modules/.bin/esbuild \
    --bundle --format=esm --platform=browser --target=es2020 \
    --minify --legal-comments=eof \
    --outfile="$out" \
    node_modules/@supabase/supabase-js/dist/module/index.js
done

# esbuild only preserves comments that are already marked legal (/*! or @license).
# Several of these packages ship none inline, so the notices come from their
# LICENSE files instead — collected here rather than assumed.
NOTICE="$UI/vendor/SUPABASE-LICENSES.txt"
{
  echo "Third-party licences for vendor/supabase.js"
  echo "==========================================="
  echo
  echo "This file is generated by scripts/vendor-supabase.sh. vendor/supabase.js is a"
  echo "bundle of the packages below; each is MIT, and MIT requires its copyright and"
  echo "permission notice to accompany any redistributed copy."
  echo
  for pkg in supabase-js auth-js postgrest-js realtime-js storage-js functions-js node-fetch; do
    dir="node_modules/@supabase/$pkg"
    [ -d "$dir" ] || continue
    ver="$(node -p "require('./$dir/package.json').version")"
    echo "-----------------------------------------------------------------------"
    echo "@supabase/$pkg $ver"
    echo "-----------------------------------------------------------------------"
    lic="$(ls "$dir"/LICENSE* 2>/dev/null | head -1)"
    if [ -n "$lic" ]; then cat "$lic"; else echo "(MIT — see https://www.npmjs.com/package/@supabase/$pkg)"; fi
    echo
  done
} > "$NOTICE"
cp "$NOTICE" "$LANDING/vendor/SUPABASE-LICENSES.txt"

# The whole point is that the bundle reaches for nothing at runtime. A remote
# import surviving it would silently restore the CDN dependency.
if grep -qE '(import|from)[[:space:]]*"https?://' "$UI/vendor/supabase.js"; then
  echo "the bundle still contains a remote import - refusing to ship it" >&2
  exit 1
fi

# A bundle that shipped without its notices would be a licence violation in every
# installer, so this is a hard check rather than a hope.
if ! grep -qi "permission is hereby granted" "$NOTICE"; then
  echo "no MIT notice was collected - refusing to ship the bundle" >&2
  exit 1
fi

echo "vendored @supabase/supabase-js@${VERSION}"
ls -l "$UI/vendor/supabase.js" "$UI/vendor/SUPABASE-LICENSES.txt"
